### ISSUE TITLE
Permission Already Registered Error (will be fixed ASAP)

### ISSUE THREAD

**Issue by BrettplayMC** [Spazzinq/FlightControl#3] opened 2019-07-24 17:43 UTC
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Describe the bug** *(if not just an error)*
 ...Getting some weird 'errors' on startup.
 
**Error** *(if there's an error, use hastebin or gist)*
 ...
 https://pastebin.com/3Ex0D5R7
**Configuration** *(hastebin or gist)*
 ...https://pastebin.com/raw/MWAVUJGS
 
**FlightControl Permissions** *(given to player)* **& OP Status**
 ...essentials.fly
 
**Server Version** *(e.g. Spigot 1.8.8)*
 ...FluxSpigot 1.8.8 (fork of Taco which is a fork of Paper which is a fork of Spigot, Flux does some stuff for Factions servers with cannons).

**Comment by Spazzinq** [comment] 2019-07-24 17:51
I have fixed this issue already, but I'm currently on vacation. Stay tuned around August when I get back!

**Comment by BrettplayMC** [comment] 2019-07-24 17:52
:/ rip.  Well as far as I know at least it doesn't cause any issues.

**Comment by Spazzinq** [comment] 2019-07-24 17:54
Yup, the problem is that I loaded permissions just in case people used PlugMan to enable it, but when loaded normally FlightControl throws a few errors.

You're correct that it doesn't cause any issues.

**Comment by BrettplayMC** [comment] 2019-07-24 17:59
Ok thanks.  I'll close this.

**Comment by Spazzinq** [comment] 2019-07-28 18:58
I'm reopening this because other people are reporting the same issue.

**Comment by Spazzinq** [comment] 2019-07-29 14:02
Code with the fix has been published!

Waiting for review of other features before release...

**Comment by Spazzinq** [comment] 2019-08-01 22:53
Woohoo! It's out now.

**Closed by Spazzinq** 2019-08-01 22:53 UTC
Labels: bug
