### ISSUE TITLE
Compatibility Problem with DeluxeCombat API

### ISSUE THREAD

**Issue by MaximeMichaud** [Spazzinq/FlightControl#9] opened 2019-12-29 07:59 UTC
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 
Yes

**Describe the bug** *(if not just an error)*
Console have error(s)

Seem to be on connection
 
**Error** *(if there's an error, use hastebin or gist)*
 https://hastebin.com/fanolufeca.cs
 
**Configuration** *(gist)*
DeluxeCombat : 
PvP_Settings:
  disable_fly: false
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
Affect my Test Account With Operator
And affect without Operator too.
 
**Server Version** *(e.g. Spigot 1.8.8)*
PaperSpigot Last Build 1.8.8

**Comment by MaximeMichaud** [comment] 2019-12-29 10:02
DeluxeCombat have problem since the last update.
org.apache.commons.lang.UnhandledException: Plugin DeluxeCombat v1.13.10 generated an exception while executing task 342
it maybe not your fault.

**Comment by Spazzinq** [comment] 2019-12-30 01:12
I'm pretty certain that the problem is with DeluxeCombat, but try this jar and let me know if the problem is fixed.
[FlightControl.zip](https://github.com/Spazzinq/FlightControl/files/4008779/FlightControl.zip)

**Comment by MaximeMichaud** [comment] 2019-12-30 02:28
> I'm pretty certain that the problem is with DeluxeCombat, but try this jar and let me know if the problem is fixed.
> [FlightControl.zip](https://github.com/Spazzinq/FlightControl/files/4008779/FlightControl.zip)

Ok thank you !
DeluxeCombat have a new update that is correcting bug(s).
I will check if your modification fix the problem.

**Comment by Spazzinq** [comment] 2019-12-30 18:22
> I think that more DeluxeCombat
Yes, the issue is now confirmed to be from DeluxeCombat.

@timderspieler Could you please help?

**Comment by timderspieler** [comment] 2019-12-30 19:32
Hey. Thank you for contacting me @Spazzinq ;)

I could add an if clause if the entered player, via the api method is null.
But can you please check if you accidently used the api method with an null object?

**Comment by Spazzinq** [comment] 2019-12-30 19:37
> 
> 
> Hey. Thank you for contacting me @Spazzinq ;)
> 
> I could add an if clause if the entered player, via the api method is null.
> But can you please check if you accidently used the api method with an null object?

I checked--the player passed to the API is never null.

**Comment by Spazzinq** [comment] 2019-12-30 19:38
@timderspieler

**Comment by timderspieler** [comment] 2019-12-30 20:19
For some reason you check if a player is in combat on your plugin startup. That causes the nullpointer.
I can add an if clause as i said

**Comment by Spazzinq** [comment] 2019-12-30 23:03
> 
> 
> For some reason you check if a player is in combat on your plugin startup. That causes the nullpointer.
> I can add an if clause as i said

@timderspieler I never call the DeluxeCombat API until a player joins. That shouldn't happen.

**Comment by Spazzinq** [comment] 2020-01-02 15:39
Fixed in the latest preview. Thanks for the help!

**Closed by Spazzinq** 2020-01-02 15:39 UTC
Labels: help wanted, invalid, more info, verify

**Comment by MaximeMichaud** [comment] 2020-01-12 04:46
https://github.com/Spazzinq/FlightControl/commit/97d964c32399dfd9cd197cd8982ea8fc58e2f0f3
4.2.3 is fixing everything :)
Thank you !
